/*
CREATED BY: KELVIN ROMAN
CREATE DATE: 05/25/2025
DESCRIPTION: DML | INSERTING DATA
*/

-- OFFICAL STATEMENTS THAT ARE REFFERED TO AS DML (STATEMENTS THAT ALTER DATA) ARE:
	-- INSERT
	-- UPDATE
	-- DELETE

INSERT INTO 
	Artist (Name)
VALUES
	("Bob Marley");
	
/*
CREATED BY: KELVIN ROMAN
CREATE DATE: 05/25/2025
DESCRIPTION: DML | UPDATING DATA
*/

-- UPDATE USING THE WHERE CLAUSE IF NOT IT WILL UPDATE THE ENTIRE TABLE

UPDATE
	Artist
SET Name = "Damien Marley"
WHERE
	ArtistId = 276;
	
/*
CREATED BY: KELVIN ROMAN
CREATE DATE: 05/25/2025
DESCRIPTION: DML | UPDATING DATA
*/

-- UPDATE USING THE WHERE CLAUSE IF NOT IT WILL UPDATE THE ENTIRE TABLE

DELETE FROM
	Artist
WHERE
	ArtistId = 276;