/* 
CREATED BY: KELVIN ROMAN
CREATE DATE: 05/22/2025
DESCRIPTION: THIS QUERY DISPLAYS ALL CUSTOMERS FIRST, LAST NAMES AND EMAIL ADDRESSES
*/

SELECT 
	FirstName AS "Customer First Name",
	LastName AS "Customer Last Name", 
	Email AS EMAIL
FROM 
	Customer
ORDER BY  
	FirstName ASC, 
	LastName DESC
LIMIT 10