/*
CREATE BY: KELVIN ROMAN
CREATE DATE: 05/24/2025
DESCRIPTION: GROUPING IN SQL, WHAT ARE THE AVERAGE INVOICE BY CITY?
*/

-- GROUP BY ALWAYS FOLLOWS THE FROM CLAUSE, RULE OF THUMB IS TO GROUP BY THE NON AGGREGATED FIELD

SELECT
	BillingCity,
	ROUND(AVG(Total), 2)
FROM 
	Invoice
GROUP BY
	BillingCity
ORDER BY
	BillingCity ASC;
	
/*
CREATE BY: KELVIN ROMAN
CREATE DATE: 05/24/2025
DESCRIPTION: GROUPING IN SQL, WHAT ARE THE AVERAGE INVOICE BY CITY FOR ONLY THE CITIES THAT START WITH L?
*/

-- GROUP BY COMES AFTER WHERE
SELECT
	BillingCity,
	ROUND(AVG(Total), 2)
FROM 
	Invoice
WHERE
	BillingCity LIKE "L%"
GROUP BY
	BillingCity
ORDER BY
	BillingCity ASC;
	
/*
CREATE BY: KELVIN ROMAN
CREATE DATE: 05/24/2025
DESCRIPTION: GROUPING IN SQL, WHAT ARE THE AVERAGE INVOICE BY CITY GREATER THAN $5.00?
*/

-- CAN NOT USE WHERE CLAUSE WITH AGGREGATE FUNCTIONS, HAVE TO USE THE HAVING KEYWORD, HAVING CLAUSE COMES AFTER THE GROUP BY
-- BASICALLY WHERE IS USED FOR NON AGGREGATE FUNCTIONS WHILE THE HAVING IS USED WITH AGGREGATE FUCNTIONS
SELECT
	BillingCity,
	ROUND(AVG(Total), 2)
FROM 
	Invoice
GROUP BY
	BillingCity
HAVING
	AVG(Total) > 5
ORDER BY
	BillingCity ASC;
	
/*
CREATE BY: KELVIN ROMAN
CREATE DATE: 05/24/2025
DESCRIPTION: GROUPING IN SQL, WHAT ARE THE AVERAGE INVOICE BY CITY GREATER THAN $5.00 FOR CITIES THAT START WITH B?
*/

SELECT
	BillingCity,
	ROUND(AVG(Total), 2)
FROM 
	Invoice
WHERE
	BillingCity LIKE "B%"
GROUP BY
	BillingCity
HAVING
	AVG(Total) > 5
ORDER BY
	BillingCity ASC;

/*
CREATE BY: KELVIN ROMAN
CREATE DATE: 05/24/2025
DESCRIPTION: GROUPING IN SQL, WHAT ARE THE AVERAGE INVOICE TOTAL BY BILLING COUNTRY AND CITY?
*/

SELECT
	BillingCountry,
	BillingCity,
	ROUND(AVG(Total), 2)
FROM 
	Invoice
GROUP BY
	BillingCountry,
	BillingCity
ORDER BY
	BillingCountry ASC;