/*
CREATED BY: KELVIN ROMAN
CREATE DATE: 05/24/2025
DESCRIPTION: SUBQUERIES | GATHER DATA ABOUT ALL INVOICES THAT ARE LESS THAN THIS AVERAGE?
*/

SELECT 
	InvoiceDate,
	BillingAddress,
	BillingCity,
	total
FROM
	Invoice
WHERE
	total <
	(SELECT AVG(total) FROM Invoice)
ORDER BY
	total DESC;
	
/*
CREATED BY: KELVIN ROMAN
CREATE DATE: 05/24/2025
DESCRIPTION: SUBQUERIES | HOW IS EACH INDIVIDUAL CITY PERFOMING AGAINST THE GLOBAL AVERAGE SALES?
*/

SELECT 
	BillingCity,
	AVG(total) AS "City Average" ,
	(SELECT AVG(total) from Invoice) AS "Global Average"
FROM
	Invoice
GROUP BY
	BillingCity
ORDER BY
	BillingCity DESC;

/*
CREATED BY: KELVIN ROMAN
CREATE DATE: 05/24/2025
DESCRIPTION: SUBQUERIES WITHOUT AGGREGATE FUNCTIONS
*/
SELECT
	InvoiceDate,
	BillingAddress,
	BillingCity
FROM
	Invoice
WHERE
	InvoiceDate > 
(SELECT 
	InvoiceDate
FROM
	Invoice
WHERE
	InvoiceId = 251);
	
/*
CREATED BY: KELVIN ROMAN
CREATE DATE: 05/25/2025
DESCRIPTION: RETURNING MULTIPLE VALUES FROM A SUBQUERY
*/

SELECT
	InvoiceDate,
	BillingAddress,
	BillingCity
FROM 
	Invoice
WHERE
	InvoiceDate IN
(SELECT
	InvoiceDate
FROM
	Invoice
WHERE
	InvoiceId IN (251, 252, 254));

/*
CREATED BY: KELVIN ROMAN
CREATE DATE: 05/25/2025
DESCRIPTION: SUBQUERIES AND DISTINCT, WHICH TRACKS ARE NOT SELLING
*/
SELECT
	TrackId,
	Composer,
	Name
FROM
	Track
WHERE
	Trackid  NOT IN
(SELECT DISTINCT
	TrackId
FROM
	InvoiceLine
ORDER BY 
	TrackId)